### ISSUE TITLE
Automation - Credentials re-encrypting

### ISSUE THREAD

**Issue by wattwood** [jenkinsci/credentials-plugin#25]
We're using Ansible to automate our Jenkins master, slaves on-demand.  We added credentials to a fresh master, then copied the secrets folder, all keys, the credentials.xml, config.xml files over for every fresh master.   However, when we fire up a new Jenkins node, and go into the credentials, any modification to an existing, or new credential results in all existing passwords, sans the one being modified or added, being re-encrypted, which is just encrypting a previous encryption. 

I've compared file by file between a working, and a re-encrypted Jenkins node.  The only difference is the credentials.xml file, all other files (keys) are exactly alike.

What am I missing?

**Comment by ror6ax** [comment]
Hi, not really an answer, but how do you produce the password hash out of raw password? I'm about to write Ansible plugin to create credentials as a part of pipeline process, but I can't find the hash generation mechanism in sources...

**Comment by zhanglianx111** [comment]
@ror6ax  Hi,your problem is solved？

**Comment by stephenc** [comment]
please use the Jenkins JIRA for issue tracking
