### ISSUE TITLE
Invalid credentials for Application ID

### ISSUE THREAD

**Issue by arielsrv** [jenkinsci/credentials-plugin#27]
Hi all,
        We found one issue about credentials for API Tokens since June 29th. Maybe they changed the interface or API v1 was finally deprecated. Also we have tried create a notify from CURL binary from shell console and was applied successfully.

More about this issue from Jenkins console output.

Invalid credentials for Application ID: 5399637
Build step 'New Relic Deployment Notifications' marked build as failure
No emails were triggered.
Finished: FAILURE

https://github.com/jenkinsci/newrelic-deployment-notifier-plugin

Thank you in advance!

Ari.-

**Comment by stephenc** [comment]
please use the Jenkins JIRA for issue tracking
