### ISSUE TITLE
Remove workaround method CredentialsProvider.getDefaultAuthenticationOf(Item)

### ISSUE THREAD

**Issue by andham** [jenkinsci/credentials-plugin#29]
I found this in the code:
```
    /**
     * Workaround method until Jenkins 1.560+ is the baseline.
     */
    @NonNull
    /*package*/ static Authentication getDefaultAuthenticationOf(Item item) {
```

As Jenkins 1.565 is now the baseline this workaround can be removed. I currently don't know how though so I'm filing this ticket so my finding doesn't get lost.

**Comment by stephenc** [comment]
please use the Jenkins JIRA for issue tracking
