### ISSUE TITLE
Strategy for unit testing plugins using credentials?

### ISSUE THREAD

**Issue by sectioneight** [jenkinsci/credentials-plugin#30]
Greetings,

I'm working on the Phabricator Differential plugin (https://github.com/uber/phabricator-jenkins-plugin) and recently converted to using this plugin. I'm working on adding more tests to my plugin and wondering if there is a documented testing strategy.

Basically, I want to be able to make credentials available for the duration of a run. My code looks something like this:

```java
@Rule public JenkinsRule j = new JenkinsRule();

@Test
public void testThing() throws Exception {
  FreeStyleProject p = j.createFreeStyleProject();
  p.getBuildWrappersList().add(wrapper); // an instance of my BuildWrapper

  // add the credentials here...

  FreeStyleBuild build = p.scheduleBuild2(0).get();
  assertEquals(Result.SUCCESS, build.getResult());
}
```

I've tried something like the following, but am probably doing it all wrong:

```java
  CredentialsStore store = new SystemCredentialsProvider.UserFacingAction().getStore();
  store.addCredentials(Domain.global(), TestUtils.getDefaultConduitCredentials());
```

Is there a document somewhere that I am missing? I have poked around the source code to try and find the best way to do this.

Thanks.

**Comment by stephenc** [comment]
Best bet is just to use a `@TestExtension public static class MyProvider extends CredentialsProvider {}`

**Comment by stephenc** [comment]
please use the Jenkins JIRA for issue tracking
