### ISSUE TITLE
Doesnt work with f:validateButton when expressionAllowed is true

### ISSUE THREAD

**Issue by aldrinleal** [jenkinsci/credentials-plugin#35]
Given this config.jelly:

```
    <f:section title="AWS Credentials and Region">
        <f:entry title="${%Credentials}" field="credentialId">
            <c:select expressionAllowed="true" />
        </f:entry>

        <f:entry title="AWS Region" field="awsRegion">
            <f:textbox default="us-east-1"/>
        </f:entry>

        <f:validateButton method="validateCredentials" title="Validate Credentials" with="credentialId,awsRegion"/>
    </f:section>
```

validateButton will always yield a blank value for credentialId whenever a value from the select is picked. The reason boils down to hudson-behaviours.js, which isn't aware of the hidden controls.

If you open the Debugger and remove the textbox manually, the expected behaviour works.

**Comment by stephenc** [comment]
please use the Jenkins JIRA for issue tracking
