### ISSUE TITLE
Get plain text secret when using a credential of kind "Secret text"

### ISSUE THREAD

**Issue by fgs-dbudwin** [jenkinsci/credentials-plugin#43]
Hello,

I'm really having a difficult time trying to get a plain text string of a credential of "Secret text."  I need the plain text representation since it's an API key that gets passed as a parameter in a URL.  I can't find many examples since I think this is a _fairly_ new feature of the plugin.

Basic example of what I'm trying...

```
//credentialsAuthToken is the ID of the token in the plugin currently
if (credentialsAuthToken != null && !credentialsAuthToken.isEmpty()) {
     StandardUsernameCredentials credentials = lookupCredentials(credentialsAuthToken);
     if (credentials != null) {
         //The question is, how do I do something like the following commented out lines (the following code compiled when the type is PasswordCredentials
         //Secret secret = credentials.getPassword();
         //if (secret != null) {
         //return secret.getPlainText();
     }
}
```

Thank you!

**Comment by halkeye** [comment]
I think your comment explains it. StandardUsernameCredentials don't have passwords do they? Don't you need a https://github.com/jenkinsci/credentials-plugin/blob/master/src/main/java/com/cloudbees/plugins/credentials/common/StandardUsernamePasswordCredentials.java or at least UsernamePasswordCredentials

**Comment by fgs-dbudwin** [comment]
Isn't `UsernamePasswordCredentials` for when you have a username and a password?  I'm using a secret, which is just that, just a secret.  How is that implemented in this plugin, I had a hard time understanding that from looking at the code locally.

**Comment by halkeye** [comment]
I've only played with credentials a bit.

How are you using a secret? you'll need to create a credentials object with the right interfaces defined, then when you consume it (which is what you saying), then you need to know which interface was used.

UsernameCredentials (and standard) afaik is just an interface that says "This credentials has a username"

**Comment by fgs-dbudwin** [comment]
In our case, the secret is an API key which by definition doesn't have a username.  The credentials plugin supports this successfully.  To create a secret in the plugin go to "Manage Credentials" then add a new credential.  For the "Kind" choose "Secret text".

> How are you using a secret? you'll need to create a credentials object with the right interfaces defined, then when you consume it (which is what you saying), then you need to know which interface was used.

I'm having a hard time determining what the interface is...the name of classes in the code don't lineup super well with the names display in the plugin which makes it really hard to find a solution.

Look for "Secret text" here for some images/description: https://cloudbees.zendesk.com/hc/en-us/articles/203802500-Injecting-Secrets-into-Jenkins-Build-Jobs

**Comment by halkeye** [comment]
Ah interesting interesting.

Could it be https://github.com/jenkinsci/plain-credentials-plugin/blob/master/src/main/java/org/jenkinsci/plugins/plaincredentials/StringCredentials.java ?

`credential instanceOf StringCredentials`?

**Comment by halkeye** [comment]
If you look at the credentials.xml directly you can see which classes they use

**Comment by fgs-dbudwin** [comment]
Ah, good find with the PlainCredentials repo.  I'll look into that and report back.

Where did you find a `credentials.xml` file?  I don't see one in either repo.

**Comment by fgs-dbudwin** [comment]
I got it working!  Thanks so much for your help, this issue can be closed!

**Comment by halkeye** [comment]
@fgs-dbudwin credentials.xml would be in your $JENKINS_HOME

awesome
