### ISSUE TITLE
Icon has wrong size

### ISSUE THREAD

**Issue by iamWh1sp3r** [jenkinsci/credentials-plugin#46]
I think this is plugin related. The credentials icon in the side-panel element has the class "icon-xlg" whilst other icons use the "icon-md" class.

![screen shot 2016-04-01 at 11 38 11 am](https://cloud.githubusercontent.com/assets/5939576/14211931/8ec5fd48-f7fe-11e5-93c1-eaf8067c7e1f.png)

**Comment by recena** [comment]
@iamWh1sp3r Are you using a theme?

**Comment by iamWh1sp3r** [comment]
Yes we are using https://github.com/jenkins-contrib-themes/jenkins-material-theme

**Comment by recena** [comment]
@iamWh1sp3r It seems it is something related to the theme plugin, not `credentials-plugin`.

**Comment by iamWh1sp3r** [comment]
@recena I found the related issue on the theme repo, sorry to have posted some noise here. Thanks!
