### ISSUE TITLE
Cann't get access to configure of node

### ISSUE THREAD

**Issue by ashashev** [jenkinsci/credentials-plugin#49]
I have one slave node. After Credentials Plugin was updated to ver. 2.0 I can't open configure of existed node and I can't add new node. When I click on "configure" loading start but nothing happens. This behavior don't depend on version Jenkins, I tried on v.2.6 and v.1.651.2.

P.S.
I'm sorry for my English.

**Comment by bjoernHeneka** [comment]
same behavior here. Adding new node runs in timeout and CPU load runs up too 100%

**Comment by cburlacu** [comment]
Same behavior here. I downgraded to 1.28 and it's working fine.

**Comment by tarzanek** [comment]
@kohsuke  can you help?

Thread t@191: (state = IN_JAVA)
 - com.cloudbees.plugins.credentials.CredentialsProvider$1$1.hasNext() @bci=150, line=515 (Compiled frame; information may be imprecise)
 - com.cloudbees.plugins.credentials.CredentialsSelectHelper.getStoreItems(boolean) @bci=49, line=109 (Interpreted frame)
 - sun.reflect.NativeMethodAccessorImpl.invoke0(java.lang.reflect.Method, java.lang.Object, java.lang.Object[]) @bci=0 (Compiled frame)

if you need more info, let me know

**Comment by tarzanek** [comment]
AH, I guess this could be closed as dup of 
15c77bf6a80636f8339cf5a422b6af422efb1183 
JENKINS-35075
@kohsuke sorry for false alarm, seems @stephenc has it under control :)

**Comment by tarzanek** [comment]
(and thank you guys for quick turnaround ;) )

**Comment by tarzanek** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-35075
fixed hpi:
"Should be available in the update center within the next 24h or can be downloaded directly from http://jenkins-updates.cloudbees.com/download/plugins/credentials/2.0.3/credentials.hpi if you need it before the update center sync
"

**Comment by ashashev** [comment]
Thank you all!

**Comment by stephenc** [comment]
Please file issues in Jenkins JIRA not here.

Also resolved as JENKINS-35075

**Comment by geripgeri** [comment]
Hi, when I try to save a new node I get this message:
HTTP 400
    This page expects a form submission

**Comment by stephenc** [comment]
<H1>STOP USING GITHUB ISSUES</H1>

The issue tracker for this project is Jenkins JIRA with the component `credentials-plugin`

**Comment by cburlacu** [comment]
I tried, created an account (https://accounts.jenkins.io/myself/). 
Cannot login on jira (https://issues.jenkins-ci.org/secure/Dashboard.jspa), but I can update my account (https://issues.jenkins-ci.org/secure/ForgotLoginDetails.jspa)

**Comment by geripgeri** [comment]
Just a friendly reminder: you could disable the issues feature in. 
`Settings -> Features ->  Issues`

**Comment by stephenc** [comment]
@geripgeri I do not have permission to disable it
