### ISSUE TITLE
Job configuration page is stuck at loading

### ISSUE THREAD

**Issue by ggirou** [jenkinsci/credentials-plugin#50]
I installed Credentials Plugin 2.0.5 and any job configuration page is stuck at loading.
I have JS error:

	TypeError: menuButton.getMenu(...) is null
		<anonymous> select.js:188
		forEach() self-hosted:232
		Behaviour.applySubtree/</<() behavior.js:111
		forEach() self-hosted:232
		Behaviour.applySubtree/<() behavior.js:107
		forEach() self-hosted:232
		Behaviour.applySubtree() behavior.js:93
		Behaviour.apply() behavior.js:76
		Behaviour.start/<() behavior.js:71
		Behaviour.addLoadEvent/window.onload() behavior.js:125

Rollback to previous version 1.28 removed this problem.

**Comment by matsbov** [comment]
I have the same problem with 2.0.5. Version 2.0 works for me.

**Comment by stephenc** [comment]
<h1>STOP USING GITHUB ISSUES</h1>

The issue tracker for this project is Jenkins JIRA with the component credentials-plugin

FTR https://issues.jenkins-ci.org/browse/JENKINS-35120 and fixed in 2.0.6

**Comment by ggirou** [comment]
Sorry for that, it's the first time I create an issue for a Jenkins plugin.

I tried to create one on the given link [Credentials Plugin issues](https://issues.jenkins-ci.org/browse/JENKINS-33314?jql=project%20%3D%20JENKINS%20AND%20status%20in%20%28Open%2C%20%22In%20Progress%22%2C%20Reopened%29%20AND%20component%20%3D%20%27credentials-plugin%27) but I didn't find any `New issue` button like GitHub. Adding one somewhere in your bugtracker even if we're not sign in could help to create issue in the right place.

Also an [issue template](https://github.com/blog/2111-issue-and-pull-request-templates) could redirect users to Jenkins bugtracker ;)

**Comment by stephenc** [comment]
Again I do not have permissions in this repo to create an issue template.

I have updated the README.md file to have an image ;-)
